service: aws-node-typescript # NOTE: update this with your service name

frameworkVersion: '3'

useDotenv: true

provider:
    name: aws
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'ap-northeast-2'}
    runtime: nodejs18.x
    timeout: 30
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        NOTION_API_KEY: ${env:NOTION_API_KEY}
        NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}

package:
    individually: true

functions:
    hello:
        handler: ./src/index.handler
        events:
            - http:
                  method: GET
                  path: notion
            # - schedule: cron(* * * * MON-FRI *)
            - schedule: rate(1 minute)

plugins:
    - serverless-esbuild
    - serverless-dotenv-plugin
    - serverless-offline

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        target: 'node18'
        packager: yarn
